### ISSUE TITLE
Unable to login to blog

### ISSUE THREAD

**Issue by bq1028** [jorisvink/kore-blog#1]
Hi Joris
First of all, thank you so much for your efforts on this blog.  and i m interested in it but now i met the problem,   

i can run blog behind nginx server,  but unable login on it,  I add user "test" with "123456" as pwd to users.conf. the format in users.conf is  test:123456.   the info below are screen dump when i run kodev.   Could you please give some tips on that.  thank you !!!

building blog (dev)
CFLAGS=-std=c99 -pedantic -O3 -Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -W
sign-compare -fPIC -Isrc -Isrc/includes -I/usr/local/include -DKORE_NO_TLS -g 
LDFLAGS=-lsodium -shared 
nothing to be done!
[parent]: running on http://0.0.0.0:8000
[parent]: kore is starting up
[wrk 0]: worker 0 started (cpu#0)
[wrk 0]: rebuilding post list
[wrk 0]: reloading users
[wrk 1]: worker 1 started (cpu#1)
[wrk 1]: rebuilding post list
[wrk 1]: reloading users
[wrk 2]: worker 2 started (cpu#0)
[wrk 2]: rebuilding post list
[wrk 2]: reloading users
[wrk 3]: worker 3 started (cpu#1)
[wrk 3]: rebuilding post list
[wrk 3]: reloading users
[wrk 0]: blog (/login/) visit from https://nowellzhang.top/login/

**Comment by bq1028** [comment]
the blog is live,  access it via https://nowellzhang.top/login/

**Comment by jorisvink** [comment]
The password needs to be an argon2 hash. 

Not plaintext.

.joris

**Comment by bq1028** [comment]
Thank you so much for your advice, Joirs!  it's incredible for so fast response. I will get right on it. thank you again!!!

**Comment by bq1028** [comment]
The blog works now and create it first blog on it,  it is really great idea to create blog.  thank you!!! Joris!

**Comment by jorisvink** [comment]
Glad it works :)

Will close this issue now.
