### ISSUE TITLE
kore-blog not a kore app

### ISSUE THREAD

**Issue by wailchalabi** [jorisvink/kore-blog#2]
after running it i get this message :
kore run: kore-blog doesn't appear to be a kore app

**Comment by ofiala-a51** [comment]
Hello,

please rename the directory from "kore-blog" to "blog". This should solve the problem.

- OF

**Comment by ofiala-a51** [comment]
(huh, why hasn't anyone answered this sooner?)

**Comment by wailchalabi** [comment]
Thanks a lot !!
