### ISSUE TITLE
[parent]: validator v_referer has undefined callback referer

### ISSUE THREAD

**Issue by Everret-moon** [jorisvink/kore-blog#3]
building blog (dev)
CFLAGS=-std=c99 -pedantic -O3 -Wall -Wextra -Werror -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -I/usr/local/include -fPIC -Isrc -Isrc/includes -I/usr/local/include -DKORE_USE_TASKS -DKORE_USE_JSONRPC -DKORE_USE_PYTHON -DKORE_USE_CURL -I/usr/include/python3.6m -I/usr/include/python3.6m -g
LDFLAGS=-L/usr/local/lib -lsodium -shared
nothing to be done!
[parent]: OpenSSL 1.0.2k-fips  26 Jan 2017 has no TLS 1.3 - will only use TLS 1.2
ignoring "server" on line 3
[parent]: running on https://127.0.0.1:9988
ignoring "tls" on line 5
[parent]: validator v_referer has undefined callback referer
bad validator specified: function
/usr/local/bin/kore: configuration error on line 13

**Comment by jorisvink** [comment]
You turned off single binary.
Not how I use the blog code, no wonder it fails to find the validator.

Since you turned off single binary you'll want to make sure you load the dso from the configuration.

**Comment by Everret-moon** [comment]
Thank you.
